// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (
  name, bio
) VALUES (
  ?, ?
)
RETURNING id
`

type CreateAuthorParams struct {
	Name string         `json:"name" validate:"required,min=3,max=100"`
	Bio  sql.NullString `json:"bio"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.Name, arg.Bio)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = ?
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio FROM authors
ORDER BY name
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsComplex = `-- name: ListAuthorsComplex :many
Select name, bio from authors
WHERE name LIKE ? and id > ?
`

type ListAuthorsComplexParams struct {
	Name string `json:"name" validate:"required,min=3,max=100"`
	ID   int64  `json:"id"`
}

type ListAuthorsComplexRow struct {
	Name string         `json:"name" validate:"required,min=3,max=100"`
	Bio  sql.NullString `json:"bio"`
}

func (q *Queries) ListAuthorsComplex(ctx context.Context, arg ListAuthorsComplexParams) ([]ListAuthorsComplexRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsComplex, arg.Name, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsComplexRow
	for rows.Next() {
		var i ListAuthorsComplexRow
		if err := rows.Scan(&i.Name, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :exec
UPDATE authors
set name = ?,
bio = ?
WHERE id = ?
`

type UpdateAuthorParams struct {
	Name string         `json:"name" validate:"required,min=3,max=100"`
	Bio  sql.NullString `json:"bio"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthor, arg.Name, arg.Bio, arg.ID)
	return err
}
